baseurl = "/"
languageCode = "en-us"
theme = "dusk"
paginate = 5

publishdir = "_deploy"

[author]
name = "Trevor Elliott"

[params]
github = "elliottt"
twitter = "moltarx"

[language]

[languages.en]
languageName = "English"
title = "trevor elliott"

[languages.en.params.logo]
logoText = "stuff and things"
logoHomeLink = "/"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "blog"
name = "blog"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 2

[[languages.en.menu.main]]
identifier = "cv"
name = "cv"
url = "/cv"
weight = 3
